name: FOSSA CLI Analysis - Ruby
on:
  pull_request:
    branches: [ $default-branch ]

jobs:
  check_env:
    runs-on: ubuntu-latest
    env:
      HAS_FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY != '' }}
    steps:
      - id: check-fossa-api-key
        run: echo "check=$HAS_FOSSA_API_KEY" >> "$GITHUB_OUTPUT"
    outputs:
      HAS_FOSSA_API_KEY: ${{ steps.check-fossa-api-key.outputs.check }}

  prep:
    needs: check_env
    if: ${{ needs.check_env.outputs.HAS_FOSSA_API_KEY == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

  fossa:
    uses: newrelic-csec/.github/.github/workflows/fossa-default.yml@reusable
    needs: prep
